# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dodam' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dodam
  pod 'SnapKit', '~> 5.0.0'

  target 'DodamTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DodamUITests' do
    # Pods for testing
  end

end
